language: node_js
node_js:
  - "8.4"
  - "10.0"
  - "10"
  - "12.0"
  - "12"
  - "node"

before_install:
  - npm install -g npm@latest
script:
  - npm run build

before_deploy:
  - echo node_modules > .gitignore
  - cp gh-pages/* dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
    condition: $TRAVIS_NODE_VERSION = 10.0

cache:
  directories:
    - node_modules
