import * as $rdf from 'rdflib'
import * as panes from 'solid-panes'
import { authn, solidLogicSingleton, authSession, store } from 'solid-logic'
import versionInfo from './versionInfo'
import './styles/mash.css'

const global: any = window
const LAYOUT_STORAGE_KEY = 'mashlib-layout'
const MOBILE_BREAKPOINT_PX = 768

type ThemeMode = 'light' | 'dark'
type LayoutMode = 'desktop' | 'mobile'
type LayoutPreference = LayoutMode | 'auto'

// Theme Management
const initializeTheme = () => {
  const savedTheme = localStorage.getItem('mashlib-theme')
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
  const theme = (savedTheme || (prefersDark ? 'dark' : 'light')) as ThemeMode
  
  if (theme === 'dark') {
    document.documentElement.setAttribute('data-theme', 'dark')
  } else {
    document.documentElement.removeAttribute('data-theme')
  }
}

const setTheme = (theme: ThemeMode) => {
  if (theme === 'dark') {
    document.documentElement.setAttribute('data-theme', 'dark')
  } else {
    document.documentElement.removeAttribute('data-theme')
  }
  localStorage.setItem('mashlib-theme', theme)
}

const getTheme = (): ThemeMode => {
  return document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light'
}

/* Generated by AI */
/*
*  Prompt on auto model: 
*  Looking at these 2 files (databrowser.html and index.ts), 
*  I want to redesign mashlib and underlying panes. 
*  I have a design for web and one for mobile. 
*  How would I go about making sure I can also have a mobile version?
*/

const getStoredLayoutPreference = (): LayoutPreference => {
  const storedLayout = localStorage.getItem(LAYOUT_STORAGE_KEY)

  if (storedLayout === 'mobile' || storedLayout === 'desktop' || storedLayout === 'auto') {
    return storedLayout
  }

  return 'auto'
}

const resolveAutomaticLayout = (): LayoutMode => {
  return window.innerWidth <= MOBILE_BREAKPOINT_PX ? 'mobile' : 'desktop'
}

const applyLayoutAttributes = (layout: LayoutMode, preference: LayoutPreference) => {
  const root = document.documentElement
  const inputMode = window.matchMedia('(pointer: coarse)').matches ? 'touch' : 'pointer'

  root.setAttribute('data-layout', layout)
  root.setAttribute('data-layout-preference', preference)
  root.setAttribute('data-input-mode', inputMode)
  root.style.setProperty('--app-height', `${window.innerHeight}px`)

  window.dispatchEvent(new CustomEvent('mashlib:layoutchange', {
    detail: {
      inputMode,
      layout,
      preference,
      viewport: {
        height: window.innerHeight,
        width: window.innerWidth
      }
    }
  }))
}

const updateLayout = (preference: LayoutPreference = getStoredLayoutPreference()): LayoutMode => {
  const layout = preference === 'auto' ? resolveAutomaticLayout() : preference
  applyLayoutAttributes(layout, preference)
  return layout
}

const setLayoutPreference = (preference: LayoutPreference): LayoutMode => {
  if (preference === 'auto') {
    localStorage.removeItem(LAYOUT_STORAGE_KEY)
  } else {
    localStorage.setItem(LAYOUT_STORAGE_KEY, preference)
  }

  return updateLayout(preference)
}

const getLayoutPreference = (): LayoutPreference => {
  return getStoredLayoutPreference()
}

const getLayoutMode = (): LayoutMode => {
  return (document.documentElement.getAttribute('data-layout') as LayoutMode) || resolveAutomaticLayout()
}

const initializeLayout = () => {
  let resizeFrame = 0
  const syncLayout = () => {
    updateLayout()
  }

  const onResize = () => {
    if (resizeFrame) {
      window.cancelAnimationFrame(resizeFrame)
    }

    resizeFrame = window.requestAnimationFrame(() => {
      resizeFrame = 0
      syncLayout()
    })
  }

  syncLayout()
  window.addEventListener('resize', onResize)

  window.matchMedia('(pointer: coarse)').addEventListener('change', syncLayout)
  window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT_PX}px)`).addEventListener('change', syncLayout)
}

/* END of Generated by AI */


// Initialize theme on load
initializeTheme()
initializeLayout()

global.$rdf = $rdf
global.panes = panes
global.SolidLogic = {
  authn,
  authSession, 
  store,
  solidLogicSingleton
}
global.mashlib = {
  versionInfo,
  layout: {
    get: getLayoutMode,
    getPreference: getLayoutPreference,
    init: initializeLayout,
    set: setLayoutPreference
  },
  theme: {
    set: setTheme,
    get: getTheme,
    init: initializeTheme
  }
}

global.panes.runDataBrowser = function (uri?:string|$rdf.NamedNode|null) {
  // Set up cross-site proxy
  const fetcher: any = $rdf.Fetcher
  fetcher.crossSiteProxyTemplate = window.origin + '/xss/?uri={uri}'

  // Add web monetization tag to page header
  try {
    const webMonetizationTag: HTMLElement = document.createElement('meta')
    webMonetizationTag.setAttribute('name', 'monetization')
    webMonetizationTag.setAttribute('content', `$${window.location.host}`)
    document.head.appendChild(webMonetizationTag)
  } catch (e) {
    console.error('Failed to add web monetization tag to page header')
  }

  // Authenticate the user
  authn.checkUser().then(function (_profile: any) {
    const mainPage = panes.initMainPage(solidLogicSingleton.store, uri)
    return mainPage
  })
}

window.onpopstate = function (_event: any) {
  global.document.outline.GotoSubject(
    $rdf.sym(window.document.location.href),
    true,
    undefined,
    true,
    undefined
  )
}

export {
  versionInfo
}
