name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Save build
        if: matrix.node-version == '16.x'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .
            !node_modules
          retention-days: 1

  gh-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: rm .gitignore
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

  npm-publish-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Append commit hash to package version
        run: 'sed -i -E "s/(\"version\": *\"[^\"]+)/\1-${GITHUB_SHA_SHORT}/" package.json'
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ env.GITHUB_REF_SLUG }}

  npm-publish-latest:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Disable pre- and post-publish actions
        run: 'sed -i -E "s/\"((pre|post)publish)/\"ignore:\1/" package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
